# Generated by Django 4.2.3 on 2023-07-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='threads',
        ),
    ]
