# Generated by Django 4.2.3 on 2023-10-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_contactcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcard',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
