# Generated by Django 4.2.3 on 2023-08-02 07:07

from django.db import migrations, models
import django.db.models.deletion
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(max_length=255)),
                ('price_period', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Package',
            },
        ),
        migrations.CreateModel(
            name='ServiceProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('up_title', models.CharField(max_length=255)),
                ('down_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to=services.uploader.Uploader.services_property_photo)),
            ],
            options={
                'verbose_name': 'Service Property',
                'verbose_name_plural': 'Service Property',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to=services.uploader.Uploader.services_logo)),
                ('photo', models.ImageField(upload_to=services.uploader.Uploader.services_photo)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServicesPropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('services_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_property_details', to='Service.serviceproperty')),
            ],
            options={
                'verbose_name': 'Services Property Details',
                'verbose_name_plural': 'Services Property Details',
            },
        ),
        migrations.AddField(
            model_name='serviceproperty',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_property', to='Service.services'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to=services.uploader.Uploader.services_category_icon)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_category', to='Service.services')),
            ],
            options={
                'verbose_name': 'Services Category',
                'verbose_name_plural': 'Services Category',
            },
        ),
        migrations.CreateModel(
            name='PackageProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to=services.uploader.Uploader.services_package_icon)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_property', to='Service.package')),
            ],
            options={
                'verbose_name': 'Package Property',
                'verbose_name_plural': 'Package Property',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='services_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_category_packages', to='Service.servicecategory'),
        ),
        migrations.CreateModel(
            name='LastWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=services.uploader.Uploader.services_category_last_works)),
                ('services_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_category_last_works', to='Service.servicecategory')),
            ],
            options={
                'verbose_name': 'Last Work',
                'verbose_name_plural': 'Last Work',
            },
        ),
    ]
