# Generated by Django 4.2.3 on 2023-10-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproperty',
            old_name='down_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='serviceproperty',
            name='up_title',
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.CharField(max_length=255),
        ),
    ]
