# Generated by Django 4.2.3 on 2023-10-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_rename_down_title_serviceproperty_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='color',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='symbol',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
