# Generated by Django 4.2.3 on 2023-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_package_color_package_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageproperty',
            name='icon',
        ),
        migrations.AddField(
            model_name='packageproperty',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
