# Generated by Django 4.2.3 on 2023-10-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_remove_packageproperty_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastworks',
            name='services_category',
        ),
        migrations.RemoveField(
            model_name='package',
            name='services_category',
        ),
        migrations.AddField(
            model_name='lastworks',
            name='services_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services_property_last_works', to='Service.serviceproperty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='services_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services_property_packages', to='Service.serviceproperty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceproperty',
            name='icon',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
