# Generated by Django 4.2.3 on 2023-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_remove_lastworks_services_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastworks',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
